package chart

import (
	"log"
	"os"

	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/go-echarts/go-echarts/v2/opts"
)

type Plot struct {
	X string
	Y opts.BarData
}

func getBarItems(plots []Plot) (Xdata []string, Ydata []opts.BarData) {
	xItems := make([]string, 0)
	yItems := make([]opts.BarData, 0)

	for _, plot := range plots {
		xItems = append(xItems, plot.X)
		yItems = append(yItems, plot.Y)
	}
	return xItems, yItems
}

func ViewInsights(plotName string, plots []Plot) {
	bar := charts.NewBar()

	bar.SetGlobalOptions(charts.WithTitleOpts(opts.Title{
		Title:    "Youtube Analytics",
		Subtitle: "Views Counts",
	}))

	xData, yData := getBarItems(plots)
	bar.SetXAxis(xData).AddSeries("Category A", yData)

	f, _ := os.Create(plotName)
	err := bar.Render(f)
	log.Panic(err)
}

// generate random data for bar chart
// func generateBarItems() []opts.BarData {
// 	items := make([]opts.BarData, 0)
// 	for i := 0; i < 7; i++ {
// 		items = append(items, opts.BarData{Value: rand.Intn(300)})
// 	}
// 	return items
// }

// func ViewInsights() {
// 	// create a new bar instance
// 	bar := charts.NewBar()
// 	// set some global options like Title/Legend/ToolTip or anything else
// 	bar.SetGlobalOptions(charts.WithTitleOpts(opts.Title{
// 		Title:    "My first bar chart generated by go-echarts",
// 		Subtitle: "It's extremely easy to use, right?",
// 	}))

// 	// Put data into instance
// 	bar.SetXAxis([]string{"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"}).
// 		AddSeries("Category A", generateBarItems()).
// 		AddSeries("Category B", generateBarItems())
// 	// Where the magic happens
// 	f, _ := os.Create("bar.html")
// 	bar.Render(f)
// }
